on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  check_code:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x' # Using '3.x' ensures compatibility, adjust if needed e.g., '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov # Install test dependencies here

    # Step to create directories and generate data
    - name: Create directories and generate data
      run: |
        mkdir data   # Create the data directory
        mkdir models # Create the models directory
        python util/generate.py # Run the script to generate data

    - name: Test with pytest
      run: |
        pytest -s tests.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html